### ISSUE TITLE
Can not change directory sing setwd('path here')

### ISSUE THREAD

**Issue by Godcreatebugs** [renanxcortes/springerQuarantineBooksR#11]
Can not open (linux) directory using setwd('path')

**Comment by renanxcortes** [comment]
Hi @Godcreatebugs , Could you post a reproducible example here with the error message?

**Comment by Godcreatebugs** [comment]
I am sorry my bad.. Its working totally fine, I was unable to navigate from root to home. It sdone. I am closing the issue
