### ISSUE TITLE
issues to install

### ISSUE THREAD

**Issue by jimoreira** [renanxcortes/springerQuarantineBooksR#13]
hi, i cannot install the package. the error: 

WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools custom from https://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\javie\AppData\Local\Temp\RtmpiazejU\remotes3c1c50251966\renanxcortes-springerQuarantineBooksR-befa138/DESCRIPTION' ...
-  preparing 'springerQuarantineBooksR':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'springerQuarantineBooksR_0.1.0.tar.gz'
   
Installing package into ‘C:/Users/javie/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'springerQuarantineBooksR' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (convertido del aviso) package 'readxl' was built under R version 3.6.3
Ejecución interrumpida
ERROR: lazy loading failed for package 'springerQuarantineBooksR'
* removing 'C:/Users/javie/Documents/R/win-library/3.6/springerQuarantineBooksR'
Error: Failed to install 'springerQuarantineBooksR' from GitHub:
  (converted from warning) installation of package ‘C:/Users/javie/AppData/Local/Temp/RtmpiazejU/file3c1c205e2eb2/springerQuarantineBooksR_0.1.0.tar.gz’ had non-zero exit status

sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252   
[3] LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readxl_1.3.1

If you have any suggestions, 
thanks for your help!

**Comment by renanxcortes** [comment]
Could you try installing `readxl` and then try installing again?

**Comment by renanxcortes** [comment]
I believe this is issue is closely related to https://github.com/renanxcortes/springerQuarantineBooksR/issues/12.

**Comment by renanxcortes** [comment]
Closing this issue, since this should be fixed with https://github.com/renanxcortes/springerQuarantineBooksR/pull/17. If this behavior is still happening, please re-open it.
