### ISSUE TITLE
Download German books

### ISSUE THREAD

**Issue by schornhe** [renanxcortes/springerQuarantineBooksR#16]
It would be great to have alos the possibility to get the German books also

**Comment by renanxcortes** [comment]
That would be cool @schornhe! However, I'm checking here that the column "German Package Name" is empty in the springer files menu (https://resource-cms.springernature.com/springer-cms/rest/v1/content/17858272/data/v4/). Is this what you're referring about?

**Comment by schornhe** [comment]
@renanxcortes : The German books are here: [https://resource-cms.springernature.com/springer-cms/rest/v1/content/17863240/data/v2](https://resource-cms.springernature.com/springer-cms/rest/v1/content/17863240/data/v2)
This is a diffrent file

**Comment by renanxcortes** [comment]
> @renanxcortes : The German books are here: https://resource-cms.springernature.com/springer-cms/rest/v1/content/17863240/data/v2
> This is a diffrent file

Ow, I see got it! Okay, I'll check here the feasibility of adding them. Thanks!

**Comment by schornhe** [comment]
@renanxcortes : There is also a third list about medical and nursing books in German: [https://resource-cms.springernature.com/springer-cms/rest/v1/content/17856246/data/v3](https://resource-cms.springernature.com/springer-cms/rest/v1/content/17856246/data/v3)
Maybe you can consider this list as well

**Comment by Nosferican** [comment]
Links and availability of epub/pdf for German textbooks ([last two columns](https://github.com/Nosferican/SpringerQuarantineBooks.jl/blob/master/data/FreeGermanTextbooksEnhanced.tsv)).

**Comment by renanxcortes** [comment]
@schornhe and @Nosferican , The last PR addresses the issue and now the function has the German books. Please, could you try running (please note the `lan = 'ger'`, which is for German language):

```
devtools::install_github("renanxcortes/springerQuarantineBooksR", force = T)
library(springerQuarantineBooksR)
setwd('different_destination_folder_for_german_books')
download_springer_book_files(lan = 'ger')
```

It will generate an output similar to this one below:

![image](https://user-images.githubusercontent.com/22593188/80667819-8deb3f00-8a76-11ea-8cfb-c78d24ad0741.png)

Please, let me know if it worked. And if yes, let your German friends know!!! :)

**Comment by renanxcortes** [comment]
I reopened this issue, but add a `partially solved` label on it. I need to check how to add the medical and nursing books that @schornhe 
 mentioned in https://github.com/renanxcortes/springerQuarantineBooksR/issues/16#issuecomment-621004526.

**Comment by schornhe** [comment]
@renanxcortes Thanks' for you efforts.
I have observed the following issues:
The program ist starting with 
`Downloading title latest editions.
Processing... Werbe- und Konsumentenpsychologie (1 out of 52)`
However in the list ...v2 are 55 books
The missing books are labeled in the column "Product Type" with "Undergraduate textbook" or "Graduate/advanced undergraduate textbook"
However in the collumn "language Collection" they are labeled with "German"

The program runs through and loads 52 books, but at th end I get the message
`Warning message:
In if (!dir.exists(current_folder)) { :
  the condition has length > 1 and only the first element will be used`

My suggestion to add the nursing books I would be:
`if (lan == 'ger_nurse') {books_list_url <- 'https://resource-cms.springernature.com/springer-cms/rest/v1/content/17863240/data/v3'}`
