### ISSUE TITLE
Evaluation error: file '...\file....xlsx' cannot be opened

### ISSUE THREAD

**Issue by stm** [renanxcortes/springerQuarantineBooksR#37]
Springer seems to have updated their list of books, therefore xlsx-file that contains the list of books is not downloaded correctly.

Changing the end of line 21 in `download_springer_table.R` from

`books_list_url <- 'https://resource-cms.springernature.com/springer-cms/rest/v1/content/17858272/data/v4/'`

to 

`books_list_url <- 'https://resource-cms.springernature.com/springer-cms/rest/v1/content/17858272/data/v5/'`

fixes the problem (i.e., replace the `v4` with **`v5`**)

**Comment by gabrielmagno** [comment]
Pull request #38 will fix this issue.
Credits goes to @stm
