### ISSUE TITLE
installation non-zero exit status

### ISSUE THREAD

**Issue by AlyeskaBear** [renanxcortes/springerQuarantineBooksR#40]
Trying to install the package (in multiple different Windows PCs) but encounter the error message 

installation of package ‘C:/Users/Tim/AppData/Local/Temp/RtmpSETARB/file3ce4752013ff/springerQuarantineBooksR_0.1.0.tar.gz’ had non-zero exit status

Any help is greatly appreciated.

**Comment by cvsbr** [comment]
Check the whole error message for any notice on missing packages. I was having the same issue as you, and it turned out that I was also getting a "there is no package called 'tictoc' " message. Installing the missing package solved my issue.

**Comment by AlyeskaBear** [comment]
> Check the whole error message for any notice on missing packages. I was having the same issue as you, and it turned out that I was also getting a "there is no package called 'tictoc' " message. Installing the missing package solved my issue.

Thanks, cvsbr. I tried again on a brand-new PC with the latest version of R just installed. I first install the devtools package, and then ran the following code 

` devtools::install_github("renanxcortes/springerQuarantineBooksR", force=T)`

This time, it returns the error message 

Error: Failed to install 'springerQuarantineBooksR' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’

It is a brand-new PC with freshly installed R. So, what can the problem? I am confused...

**Comment by cvsbr** [comment]
Looks like something is preventing you from updating the 'rlang' package. Try following the different solutions [here](https://community.rstudio.com/t/unable-to-update-rlang/45955/3) and see if one of them solves your problem.

**Comment by AlyeskaBear** [comment]
> Looks like something is preventing you from updating the 'rlang' package. Try following the different solutions [here](https://community.rstudio.com/t/unable-to-update-rlang/45955/3) and see if one of them solves your problem.

The weird thing is it is a new PC with R installed for the first time. So, I don't think there is any previous 'rlang' package. I have opened this as a new issue.

**Comment by CISMat** [comment]
Try installing the latest R version (R-4.0.0), then install the "devtools" and "tictoc" package ... Finally run the code:

devtools::install_github("renanxcortes/springerQuarantineBooksR", force = TRUE)

library(springerQuarantineBooksR)

**Comment by renanxcortes** [comment]
I think the solution of https://github.com/renanxcortes/springerQuarantineBooksR/issues/41 can be applied to this uses. Therefore, I'm closing it for now. Feel free to reopen It if it is not the case.
