### ISSUE TITLE
Error: Failed to install 'springerQuarantineBooksR'

### ISSUE THREAD

**Issue by indikasirimanna** [renanxcortes/springerQuarantineBooksR#42]
package ‘rlang’ successfully unpacked and MD5 sums checked
Error: Failed to install 'springerQuarantineBooksR' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by renanxcortes** [comment]
Please take a look at https://github.com/renanxcortes/springerQuarantineBooksR/issues/41 to see if that helps. I'm closing this issue due to duplication. Feel free to open it if that solution does not apply in your case.

**Comment by indikasirimanna** [comment]
Awesome Working thanks a lot :)
