### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jabv2015** [renanxcortes/springerQuarantineBooksR#45]
After updating all packages, included dplyr, I am still getting the same error:
Error: (converted from warning) package 'dplyr' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'springerQuarantineBooksR'
* removing 'C:/Program Files/R/R-3.6.1/library/springerQuarantineBooksR'
Error: Failed to install 'springerQuarantineBooksR' from GitHub:
  (converted from warning) installation of package ‘C:/Users/n9675230/AppData/Local/Temp/Rtmpw3buJ7/file251c4f0151/springerQuarantineBooksR_0.1.0.tar.gz’ had non-zero exit status

Any suggestion how to proceed?

Thanks for your great work!!

**Comment by renanxcortes** [comment]
Hi @jabv2015 , could you take a look at https://github.com/renanxcortes/springerQuarantineBooksR/issues/43? It is the problem you're and hopefully, the same solution will work!

Cheers,
Renan

**Comment by theiman112860** [comment]
Hi,

I also am having the same problem. Below is my sessioninfo:


Error: Failed to install 'springerQuarantineBooksR' from GitHub:   (converted from warning) installation of package ‘C:/Users/Owner/AppData/Local/Temp/RtmpgTdsvv/file25d871644492/springerQuarantineBooksR_0.1.0.tar.gz’ had non-zero exit status > sessionInfo() R version 3.6.1 (2019-07-05) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows >= 8 x64 (build 9200)  Matrix products: default  Random number generation:  RNG:     Mersenne-Twister   Normal:  Inversion   Sample:  Rounding    locale: [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] devtools_2.3.0 usethis_1.6.0   loaded via a namespace (and not attached):  [1] magrittr_1.5      pkgload_1.0.2     R6_2.4.1          rlang_0.4.6       fansi_0.4.1       tools_3.6.1        [7] pkgbuild_1.0.8    sessioninfo_1.1.1 cli_2.0.2         withr_2.2.0       ellipsis_0.3.0    remotes_2.1.1     [13] yaml_2.2.1        assertthat_0.2.1  digest_0.6.25     rprojroot_1.3-2   crayon_1.3.4      processx_3.4.2    [19] callr_3.4.3       fs_1.4.1          ps_1.3.3          curl_4.3          testthat_2.3.2    memoise_1.1.0     [25] glue_1.4.0        compiler_3.6.1    desc_1.2.0        backports_1.1.6   prettyunits_1.1.1 > library(janitor)  Attaching package: ‘janitor’  The following objects are masked from ‘package:stats’:      chisq.test, fisher.test  Warning message: package ‘janitor’ was built under R version 3.6.3
--
 Any ideas? Thank you! 

Ciao,

tom

**Comment by renanxcortes** [comment]
Could you try pasting your error message between three signs: `?

Therefore, GitHub can render properly like this:

```
some code snippet
````

Like this:
![image](https://user-images.githubusercontent.com/22593188/81576534-bf211480-937e-11ea-9570-eeb6d140b952.png)


Also, please paste the entire error message, if possible. 

Cheers,
Renan

**Comment by theiman112860** [comment]
Sorry. Here it is:

...
> devtools::install_github("renanxcortes/springerQuarantineBooksR",force = T) Downloading GitHub repo renanxcortes/springerQuarantineBooksR@master 
√  checking for file 'C:\Users\Owner\AppData\Local\Temp\RtmpgTdsvv\remotes25d8671f29e9\renanxcortes-springerQuarantineBooksR-48642ee/DESCRIPTION' ... -  preparing 'springerQuarantineBooksR': √  checking DESCRIPTION meta-information ...  -  checking for LF line-endings in source and make files and shell scripts -  checking for empty or unneeded directories -  building 'springerQuarantineBooksR_0.1.0.tar.gz'     Installing package into ‘C:/Users/Owner/Documents/R/win-library/3.6’ (as ‘lib’ is unspecified) * installing *source* package 'springerQuarantineBooksR' ... ** using staged installation ** R ** inst ** byte-compile and prepare package for lazy loading Error: (converted from warning) package 'dplyr' was built under R version 3.6.3 Execution halted ERROR: lazy loading failed for package 'springerQuarantineBooksR' * removing 'C:/Users/Owner/Documents/R/win-library/3.6/springerQuarantineBooksR' Error: Failed to install 'springerQuarantineBooksR' from GitHub:   (converted from warning) installation of package ‘C:/Users/Owner/AppData/Local/Temp/RtmpgTdsvv/file25d871644492/springerQuarantineBooksR_0.1.0.tar.gz’ had non-zero exit status > sessionInfo() R version 3.6.1 (2019-07-05) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows >= 8 x64 (build 9200)  Matrix products: default  Random number generation:  RNG:     Mersenne-Twister   Normal:  Inversion   Sample:  Rounding    locale: [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] devtools_2.3.0 usethis_1.6.0   loaded via a namespace (and not attached):  [1] magrittr_1.5      pkgload_1.0.2     R6_2.4.1          rlang_0.4.6       fansi_0.4.1       tools_3.6.1        [7] pkgbuild_1.0.8    sessioninfo_1.1.1 cli_2.0.2         withr_2.2.0       ellipsis_0.3.0    remotes_2.1.1     [13] yaml_2.2.1        assertthat_0.2.1  digest_0.6.25     rprojroot_1.3-2   crayon_1.3.4      processx_3.4.2    [19] callr_3.4.3       fs_1.4.1          ps_1.3.3          curl_4.3          testthat_2.3.2    memoise_1.1.0     [25] glue_1.4.0        compiler_3.6.1    desc_1.2.0        backports_1.1.6   prettyunits_1.1.1 > library(janitor)  Attaching package: ‘janitor’  The following objects are masked from ‘package:stats’:      chisq.test, fisher.test  Warning message: package ‘janitor’ was built under R version 3.6.3

...
 



...

...

**Comment by renanxcortes** [comment]
Your error is due to 

```
package 'dplyr' was built under R version 3.6.3
```

Which seems the same as https://github.com/renanxcortes/springerQuarantineBooksR/issues/43.
Please, try to update your R to 3.6.3 and try again the installation.

**Comment by theiman112860** [comment]
The gui of Rstudio was insisting that I was using 3.6.3 and the sessionInfo() said I was using 3.6.1.. Anyway it works now. Thank you!!

**Comment by renanxcortes** [comment]
Nice, cool!
