### ISSUE TITLE
Invalid Color Space error from Adobe Reader

### ISSUE THREAD

**Issue by valentinitnelav** [renanxcortes/springerQuarantineBooksR#6]
Thanks for creating this package and helping people with bulk downloading.

I installed, then loaded the package and then I executed `download_springer_book_files(parallel = TRUE)` as suggested in your [README](https://github.com/renanxcortes/springerQuarantineBooksR/blob/master/README.md)

It downloads almost 7.5 Gb of PDFs in the default folder 'springer_quarantine_books', however, trying to open some of them with Adobe Acrobat Reader DC version 2020.006.20042, I get the following errors, from case to case, e.g.:

- for './springer_quarantine_books/Computer Science/A Beginners Guide to Python 3 Programming - 1st ed. 2019.pdf':

> - "There was an error processing a page. Invalid ColorSpace"
> I click OK and the PDF is blank with an gray background.

- for './springer_quarantine_books/Behavioral Science/A Clinical Guide to the Treatment of the Human Stress Response - 3rd ed. 2013.pdf':

> - "Cannot extract the embedded font 'Times-Roman'. Some characters may not display or print correctly."
I click OK then I get further: 
>- "A drawing error occurred.". Click OK, then:
>- "An error exists on this page. Acrobat may not display the page correctly. Please contact the person who created the PDF document to correct the problem." 
In the end the PDF is blank with a white background.
I get a similar error for './springer_quarantine_books\Business and Economics/Corporate Social Responsibility - 2013.pdf', but instead of referring to font 'Times-Roman', it mentions font IHMLIA+AdvP6975 (I presume this will vary from PDF to PDF).

When I download these books directly from Springer's [link](https://link.springer.com/search?facet-content-type=%22Book%22&package=mat-covid19_textbooks&%23038;facet-language=%22En%22&%23038;sortOrder=newestFirst&%23038;showAll=true), I do not get the errors and the PDF can be read.

Any idea what might have happened?

Thanks so much for your support and help.

``` r
sessionInfo()
#> R version 3.6.2 (2019-12-12)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 18362)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.6.2  magrittr_1.5    tools_3.6.2     htmltools_0.4.0
#>  [5] yaml_2.2.1      Rcpp_1.0.4.6    stringi_1.4.6   rmarkdown_2.1  
#>  [9] highr_0.8       knitr_1.28      stringr_1.4.0   xfun_0.13      
#> [13] digest_0.6.25   rlang_0.4.5     evaluate_0.14
```

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by renanxcortes** [comment]
Hi, @valentinitnelav, thank you for pointing that out! Indeed, I checked here locally and this issue is happening pretty often. I'll downgrade to a previous version of the package and inspect what be happening. I this issue is happening after https://github.com/renanxcortes/springerQuarantineBooksR/pull/4, I'll double-check here.

**Comment by renanxcortes** [comment]
Hi, @valentinitnelav, thank you for pointing that out! Indeed, I checked here locally and this issue is happening pretty often. I have a sense that this behaviour was introduced in https://github.com/renanxcortes/springerQuarantineBooksR/pull/4.

**Comment by renanxcortes** [comment]
Hello, @valentinitnelav, I tweaked the functions to their previous versions and these issues might be fixed now. Could you re-install the package and double-check if this happens in your side?

Try running:

```
devtools::install_github("renanxcortes/springerQuarantineBooksR", force = T)
library(springerQuarantineBooksR)
setwd('different_destination_folder')
download_springer_book_files()
```

Feel free to open any other issue! Thanks!

**Comment by valentinitnelav** [comment]
Hi @renanxcortes , yes, the above code seems to work. Thanks!

**Comment by renanxcortes** [comment]
Hey, Valentin,


Could you suppress the "parallel = TRUE" argument? As I wrote some
e-mails before, this argument is not working anymore!

Best,
Renan Xavier Cortes
Data Scientist
Personal Website: https://renanxcortes.github.io/
GitHub: https://github.com/renanxcortes
LinkedIn: https://www.linkedin.com/in/renan-cortes-a3583a33/?locale=en_US



Em seg., 27 de abr. de 2020 às 05:53, Valentin Ștefan <
notifications@github.com> escreveu:
