### ISSUE TITLE
Code is not working 

### ISSUE THREAD

**Issue by DrAlqahtani** [renanxcortes/springerQuarantineBooksR#7]
I have tried the package But it does not work. Then, I open the source code and change it a little. After the modification, It works fine 

More explenation in this file 

https://docs.google.com/document/d/1kqVkQDah3CtqHT1ejafI5HLxardKa8GI1D5gjuxmoW0/edit

**Comment by renanxcortes** [comment]
Hi, @DrAlqahtani , thanks for opening this issue. What is the error message that appeared to you? I've committed some bug fixes **this morning**. Could you try running again the following code:

```
# Add 'force = T' argument
devtools::install_github("renanxcortes/springerQuarantineBooksR", force = T)
library(springerQuarantineBooksR)
setwd("/Users/khaledalqahtani/Desktop/Book")
download_springer_book_files()
```

Did it work in your side?

**Comment by renanxcortes** [comment]
This issue also should be fixed by now. Please feel free to open another one, if you experience any other issue.

**Comment by AlexBustos** [comment]
Hi renanxcortes,

thanks for shareing the code, but I have trying to use it and ... doesn´t work

Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: namespace ‘rlang’ 0.4.0 is already loaded, but >= 0.4.1 is required

Could you check it? please

**Comment by renanxcortes** [comment]
> 0.4.1

Hi @AlexBustos , can you try installing a newer version of `rlang` and then try to run again? Try running first:


```
require(devtools)
install_version("rlang", version = "0.4.1")
```
