### ISSUE TITLE
Same book is downloaded (all books) 

### ISSUE THREAD

**Issue by ahasverus** [renanxcortes/springerQuarantineBooksR#8]
Great package!
I tried the function `download_springer_book_files()` but it seems that the same book is downloaded (the file name is correct). An issue with the URL maybe?
Package installed 1 hour ago.

**Comment by renanxcortes** [comment]
Hello @ahasverus , thanks for opening this issue. Indeed, this behavior was happening, and **this morning** I commited some bug fixes. Could you please try to install the package again and run the function?

Try running the code below:

```
# Add 'force = T' argument
devtools::install_github("renanxcortes/springerQuarantineBooksR", force = T)
library(springerQuarantineBooksR)
setwd("ahasverus_specific_repo")
download_springer_book_files()
```

Please let me know if this behavior happens after reinstalling it.

**Comment by ahasverus** [comment]
Hi @renanxcortes,
I re-download your package (without `force = TRUE` as you made some modifications after my installation) and it solves the issue.
Many thanks!
